// src/constants/permissions.js
export const PERMISSIONS = {
  CREATE_EVENTS: 'CAN_CREATE_EVENTS',
  EDIT_EVENTS: 'CAN_EDIT_EVENTS',
  DELETE_EVENTS: 'CAN_DELETE_EVENTS',
  SCAN_QR: 'CAN_SCAN_QR_ANYWHERE',
  MANAGE_PARTICIPANTS: 'CAN_MANAGE_PARTICIPANTS',
  MANAGE_TEAMS: 'CAN_MANAGE_EVENT_TEAMS',
};